@database = BigBoxStore 
@collection = GroceryInventory
@domain = http://localhost
@port = 3000
###
GET {{domain}}:{{port}}/find/{{database}}/{{collection}}
Content-Type: application/json

###
POST {{domain}}:{{port}}/insert/{{database}}/{{collection}}
Content-Type: application/json

{
  "document": {
    "item": "steak",
    "food_group": "meat",
    "price_in_usd": 23.0,
    "quantity": 43,
    "calories_per_100g": 321
  }
}

###
@id = 672189198b014f93b77159c5
DELETE {{domain}}:{{port}}/delete/{{database}}/{{collection}}/{{id}}
Content-Type: application/json